// Curated list of common airlines for autocomplete.
// Users can type any custom value if their airline isn't in this list.

export const AIRLINES: string[] = [
  // North America
  "American Airlines",
  "Delta Air Lines",
  "United Airlines",
  "Southwest Airlines",
  "JetBlue Airways",
  "Alaska Airlines",
  "Spirit Airlines",
  "Frontier Airlines",
  "Hawaiian Airlines",
  "Air Canada",
  "WestJet",
  "Aeromexico",
  // Latin America
  "LATAM Airlines",
  "Avianca",
  "Copa Airlines",
  "Azul",
  "GOL",
  "Aerolíneas Argentinas",
  // Europe
  "Air France",
  "British Airways",
  "Lufthansa",
  "KLM",
  "Iberia",
  "Alitalia",
  "ITA Airways",
  "Swiss",
  "Austrian Airlines",
  "TAP Air Portugal",
  "Vueling",
  "Ryanair",
  "easyJet",
  "Wizz Air",
  "Norwegian",
  "SAS",
  "Finnair",
  "Aer Lingus",
  "Turkish Airlines",
  "Aegean Airlines",
  // Middle East
  "Emirates",
  "Qatar Airways",
  "Etihad Airways",
  "Saudia",
  "EL AL",
  // Asia / Pacific
  "Singapore Airlines",
  "Cathay Pacific",
  "ANA",
  "Japan Airlines",
  "Korean Air",
  "Asiana Airlines",
  "China Airlines",
  "EVA Air",
  "Air China",
  "China Eastern",
  "China Southern",
  "Thai Airways",
  "Malaysia Airlines",
  "AirAsia",
  "Vietnam Airlines",
  "Garuda Indonesia",
  "Philippine Airlines",
  "Qantas",
  "Air New Zealand",
  // Africa
  "Ethiopian Airlines",
  "Kenya Airways",
  "EgyptAir",
  "South African Airways",
  "Royal Air Maroc",
];
