// Cascade-delete helper for homeNote rows. Same shape as
// lib/reminder-parent.ts — when a task / event / trip is deleted from
// the UI, its linked notes are removed too. Accepts `any` for the
// client to stay compatible with both userPool and IAM auth modes.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DataClient = any;

interface NoteRow {
  id: string;
}

/**
 * Delete every homeNote linked to `parentId`. Safe to call when no
 * notes exist — the list filter just returns empty. Uses generic
 * list+filter (not the autogenerated listByField) per the lowercase-
 * model bug; see feedback_amplify_listbyfield_lowercase_bug.
 */
export async function cascadeDeleteNotesFor(
  client: DataClient,
  parentId: string
): Promise<void> {
  const { data } = await client.models.homeNote.list({
    filter: { parentId: { eq: parentId } },
  });
  for (const n of (data ?? []) as NoteRow[]) {
    await client.models.homeNote.delete({ id: n.id });
  }
}
