#!/usr/bin/env node
// Create a Cognito user and add them to the home-users group (and optionally
// admins). Works against either the sandbox (dev) or the prod main-branch
// user pool. Shells out to the AWS CLI rather than pulling in the Cognito
// SDK — keeps dependencies lean since this is an admin tool.
//
// Usage:
//   node scripts/create-user.mjs --env dev --email foo@bar.com --name "Foo Bar"
//   node scripts/create-user.mjs --env prod --email foo@bar.com --name "Foo Bar" --admin
//
// Flags:
//   --env <dev|prod>   Default: dev. Determines which user pool to use.
//   --email <email>    Required. Becomes the username.
//   --name <name>      Required. Stored as custom:full_name.
//   --password <pw>    Optional. If omitted, prompts interactively. Set as
//                      permanent (no reset-on-login).
//   --admin            Also add to the "admins" group. Always adds to
//                      "home-users".
//   --profile <name>   AWS CLI profile. Default: amplify-dev.
//   --app-id <id>      Override Amplify app id for --env prod. Defaults to
//                      dkiwlyw3k1yfi (this app).
//
// Requires:
//   - aws CLI in PATH
//   - profile with Cognito admin permissions on the target pool
//   - for dev: local amplify_outputs.json generated by `ampx sandbox`

import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

// ── Arg parsing ──────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--admin") {
      args.admin = true;
    } else if (a === "--help" || a === "-h") {
      args.help = true;
    } else if (a.startsWith("--") && i + 1 < argv.length) {
      args[a.slice(2)] = argv[++i];
    }
  }
  return args;
}

function printUsage() {
  console.log(`Usage: node scripts/create-user.mjs [options]

Required:
  --email <email>      Email address (becomes username)
  --name <name>        Full name (stored as custom:full_name)

Options:
  --env <dev|prod>     Target environment (default: dev)
  --password <pw>      Password (prompts if omitted)
  --admin              Also add to admins group
  --profile <name>     AWS CLI profile (default: amplify-dev)
  --app-id <id>        Amplify app id for prod (default: dkiwlyw3k1yfi)
  -h, --help           Show this message
`);
}

// ── Pool resolution ──────────────────────────────────────────────────────────

function resolvePoolForDev() {
  const path = resolve(repoRoot, "amplify_outputs.json");
  let raw;
  try {
    raw = readFileSync(path, "utf-8");
  } catch (err) {
    throw new Error(
      `Cannot read ${path}. Run 'npx ampx sandbox --profile amplify-dev' first to generate it.`
    );
  }
  const outputs = JSON.parse(raw);
  const poolId = outputs?.auth?.user_pool_id;
  const region = outputs?.auth?.aws_region;
  if (!poolId || !region) {
    throw new Error(
      "amplify_outputs.json is missing auth.user_pool_id or auth.aws_region"
    );
  }
  return { poolId, region, source: `sandbox (${path})` };
}

function resolvePoolForProd(profile, appId) {
  // Find the auth nested stack for the main branch.
  const listCmd = `aws cloudformation list-stacks --profile ${profile} --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --output json`;
  const listOut = execSync(listCmd, { encoding: "utf-8" });
  const summaries = JSON.parse(listOut).StackSummaries ?? [];
  const authStack = summaries.find(
    (s) => s.StackName.includes(appId) && s.StackName.includes("auth")
  );
  if (!authStack) {
    throw new Error(
      `Could not find a CREATE_COMPLETE/UPDATE_COMPLETE auth stack for app ${appId}. Deploy the prod branch first.`
    );
  }

  const descCmd = `aws cloudformation describe-stacks --stack-name ${authStack.StackName} --profile ${profile} --output json`;
  const descOut = execSync(descCmd, { encoding: "utf-8" });
  const outputs = JSON.parse(descOut).Stacks?.[0]?.Outputs ?? [];
  // The output key is a generated mouthful like
  // amplifyXXXauthamplifyAuthUserPool19ACE249Ref. Pattern-match on
  // "UserPool" + "Ref" (and NOT the App Client or Identity Pool refs).
  const poolOut = outputs.find(
    (o) =>
      /UserPool\w*Ref$/.test(o.OutputKey) &&
      !/AppClient/.test(o.OutputKey) &&
      !/IdentityPool/.test(o.OutputKey)
  );
  if (!poolOut) {
    throw new Error(
      `Auth stack ${authStack.StackName} has no UserPoolId output — did the stack structure change?`
    );
  }
  // Region is implicit in the Cognito pool id prefix (us-east-1_XXXXX).
  const region = poolOut.OutputValue.split("_")[0];
  return {
    poolId: poolOut.OutputValue,
    region,
    source: `prod (${authStack.StackName})`,
  };
}

// ── AWS CLI helpers ──────────────────────────────────────────────────────────

function awsCognito(subcmd, poolId, args, profile) {
  // Build the command carefully — values are passed through without shell
  // interpretation for safety (e.g. passwords with special chars).
  const parts = [
    "aws",
    "cognito-idp",
    subcmd,
    "--user-pool-id",
    poolId,
    "--profile",
    profile,
    "--output",
    "json",
    ...args,
  ];
  // Use execSync with array form via sh -c? Actually execSync doesn't
  // accept an array, it takes a shell string. We need to quote properly.
  const cmd = parts
    .map((p) => {
      // Simple shell quoting: wrap in single quotes, escape embedded quotes.
      if (/^[a-zA-Z0-9@._\-:=/+]+$/.test(p)) return p;
      return `'${p.replace(/'/g, `'"'"'`)}'`;
    })
    .join(" ");
  try {
    const out = execSync(cmd, { encoding: "utf-8", stdio: ["ignore", "pipe", "pipe"] });
    return { ok: true, data: out ? JSON.parse(out) : null };
  } catch (err) {
    const stderr = err.stderr?.toString() ?? "";
    return { ok: false, stderr };
  }
}

function awsCognitoOrThrow(subcmd, poolId, args, profile) {
  const res = awsCognito(subcmd, poolId, args, profile);
  if (!res.ok) {
    throw new Error(`aws cognito-idp ${subcmd} failed:\n${res.stderr}`);
  }
  return res.data;
}

/**
 * Check if a user exists in the pool. Uses admin-get-user which returns
 * 200 + user details if present, or UserNotFoundException if not. We
 * prefer this over catching UsernameExistsException from admin-create-user
 * because it gives us the detailed error once and is explicit.
 */
function userExists(email, poolId, profile) {
  const res = awsCognito(
    "admin-get-user",
    poolId,
    ["--username", email],
    profile
  );
  if (res.ok) return true;
  if (res.stderr.includes("UserNotFoundException")) return false;
  // Any other error should bubble — likely a permissions or config issue
  // that we don't want to swallow.
  throw new Error(`admin-get-user failed:\n${res.stderr}`);
}

// ── Password prompt ──────────────────────────────────────────────────────────

async function promptPassword() {
  // Node's readline doesn't natively hide input. For an internal dev tool
  // we accept visible input — it's ephemeral and the alternative is adding
  // a native dep.
  const rl = createInterface({ input, output });
  console.log(
    "No --password given. Enter a password (will be set as permanent, no reset-on-login):"
  );
  const pw = await rl.question("Password: ");
  rl.close();
  return pw;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv);
  if (args.help || !args.email || !args.name) {
    printUsage();
    process.exit(args.help ? 0 : 1);
  }

  const env = args.env ?? "dev";
  if (env !== "dev" && env !== "prod") {
    console.error(`Invalid --env "${env}". Must be "dev" or "prod".`);
    process.exit(1);
  }
  const profile = args.profile ?? "amplify-dev";
  const appId = args["app-id"] ?? "dkiwlyw3k1yfi";

  // Resolve target pool
  const { poolId, region, source } =
    env === "dev" ? resolvePoolForDev() : resolvePoolForProd(profile, appId);

  console.log(`→ Target: ${env} — ${source}`);
  console.log(`  pool:    ${poolId}`);
  console.log(`  region:  ${region}`);
  console.log(`  profile: ${profile}`);
  console.log(`  email:   ${args.email}`);
  console.log(`  name:    ${args.name}`);
  console.log(`  admin:   ${args.admin ? "yes" : "no"}`);
  console.log();

  const password = args.password ?? (await promptPassword());
  if (!password || password.length < 8) {
    console.error("Password must be at least 8 characters.");
    process.exit(1);
  }

  // 1. Create the user if missing, otherwise update password in place.
  //    Idempotent: rerunning the script with the same email is safe and
  //    useful for password resets. Group memberships are always
  //    re-asserted since admin-add-user-to-group is idempotent per AWS docs.
  const existing = userExists(args.email, poolId, profile);
  if (existing) {
    console.log(
      `User ${args.email} already exists — updating password and group memberships.`
    );
  } else {
    console.log("Creating user…");
    awsCognitoOrThrow(
      "admin-create-user",
      poolId,
      [
        "--username",
        args.email,
        "--user-attributes",
        `Name=email,Value=${args.email}`,
        `Name=email_verified,Value=true`,
        `Name=custom:full_name,Value=${args.name}`,
        "--message-action",
        "SUPPRESS",
      ],
      profile
    );
  }

  // 2. Set the password as permanent so the user can log in directly.
  //    Works the same for new and existing users.
  console.log("Setting permanent password…");
  awsCognitoOrThrow(
    "admin-set-user-password",
    poolId,
    ["--username", args.email, "--password", password, "--permanent"],
    profile
  );

  // 3. Add to home-users (always) and admins (if flagged).
  //    admin-add-user-to-group is idempotent per AWS docs — safe to
  //    call on every run.
  console.log("Adding to home-users group…");
  awsCognitoOrThrow(
    "admin-add-user-to-group",
    poolId,
    ["--username", args.email, "--group-name", "home-users"],
    profile
  );
  if (args.admin) {
    console.log("Adding to admins group…");
    awsCognitoOrThrow(
      "admin-add-user-to-group",
      poolId,
      ["--username", args.email, "--group-name", "admins"],
      profile
    );
  }

  console.log();
  console.log(
    `✓ User ${args.email} ${existing ? "updated" : "created"} successfully in ${env}`
  );
  console.log(`  Login at ${env === "prod" ? "https://home.cristinegennaro.com" : "http://localhost:3001"}`);
}

main().catch((err) => {
  console.error(`\n✗ ${err.message ?? err}`);
  process.exit(1);
});
